kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: default
data:
  stream-snippets: |
    resolver 8.8.8.8 valid=5s;
    server {
        listen 12345;
        listen [::]:12345;
        zone_sync;
        zone_sync_server nginx-ingress-headless.nginx-ingress.svc.cluster.local:12345 resolve;
    }
  resolver-addresses: 8.8.8.8
  resolver-valid: 5s
