apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: oidc-policy
spec:
  oidc:
    clientID: my-client-id
    clientSecret: oidc-secret
    authEndpoint: http://keycloak.example.com:8080/auth/realms/master/protocol/openid-connect/auth
    tokenEndpoint: http://keycloak.example.com:8080/auth/realms/master/protocol/openid-connect/token
    jwksURI: http://keycloak.example.com:8080/auth/realms/master/protocol/openid-connect/certs
    scope: openid+profile+email
    accessTokenEnable: true
